name: Run Script

on:
  workflow_dispatch:
  schedule:
    - cron: '9 1,7,10,12,14,23 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout codes
        uses: actions/checkout@v5  # 最新版，原生支持Node.js 24
        with:
          fetch-depth: 0

      - name: Update system and install zsh
        run: |
          sudo apt update && sudo apt install -y zsh

      - name: 初始化Python
        uses: actions/setup-python@v6  # 最新版，原生支持Node.js 24
        with:
          python-version: "3.10"

      - name: 开始
        run: |
          pip3 install requests pytz pycryptodome
          python3 main.py
        env:
          CONFIG: ${{ secrets.CONFIG }}
          AES_KEY: ${{ secrets.AES_KEY }}

      - name: persist tokens
        run: |
          git config user.name github-actions
          git config user.email "actions@github.com"
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "chore: update tokens [skip ci]"
            git push
          else
            echo "✅ No changes to commit, skip this step"
            exit 0
          fi
